pos_im_path = 'persons/pos'
neg_im_path = 'persons/neg'
min_wdw_sz = [64, 128]
step_size = [10,10]#sample image size
orientations = 9
pixels_per_cell = [6,6]
cells_per_block = [2, 2]
visualize = False
normalize = True
pos_feat_ph = 'features/pos_mod'
neg_feat_ph = 'features/neg_mod'
model_path = 'models'
threshold = .3
